blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¡ Suggest a feature"
    url: https://github.com/magit/magit/discussions
    about: Start a discussion suggest an improvement or a new feature.
  - name: "ğŸ†˜ Ask the community for support"
    url: https://www.reddit.com/r/emacs
    about: Please also consider supporting others.
  - name: "ğŸ†˜ Ask the maintainers for support"
    url: https://github.com/magit/magit/discussions
    about: Please keep in mind that our bandwidth is limited.
  - name: "â„¹ï¸ Magit FAQ"
    url: https://magit.vc/manual/magit/FAQ.html
    about: Others might have had the same question before.
  - name: "â„¹ï¸ Magit Manual"
    url: https://magit.vc/manual/magit/#Top
    about: The fine manual may also be of use.
