name: Manual
on:
  push:
    branches: main
    tags: "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  manual:
    name: Manual
    uses: emacscollective/workflows/.github/workflows/manual.yml@main
    secrets:
      rclone_config: ${{ secrets.RCLONE_CONFIG }}
