name: test
on: [ push, pull_request ]
env:
  BUILD_MAGIT_LIBGIT: "false"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
        - 25.1
        - 25.3
        - 26.1
        - 26.2
        - 26.3
        - 27.1
        - 27.2
        - 28.1
        - snapshot
    steps:
    - name: Configure git
      run: |
        git config --global user.name "A U Thor"
        git config --global user.email a.u.thor@example.com
    - name: Install emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Checkout compat
      uses: actions/checkout@v2
      with:
        repository: emacs-compat/compat
        path: compat
    - name: Checkout dash
      uses: actions/checkout@v2
      with:
        repository: magnars/dash.el
        path: dash
    - name: Checkout transient
      uses: actions/checkout@v2
      with:
        repository: magit/transient
        path: transient
    - name: Checkout with-editor
      uses: actions/checkout@v2
      with:
        repository: magit/with-editor
        path: with-editor
    - name: Checkout magit
      uses: actions/checkout@v2
      with:
        repository: magit/magit
        path: magit
    - name: Build compat
      run: make -C compat compile
    - name: Build magit
      run: make -C magit all
    - name: Test magit
      run: make -C magit test
